version: '3.8'
services:
  db:
    build: ./mysql/
    volumes:
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_ROOT_HOST: '%'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    networks:
      - app_network
  appserver:
    build:
      context: ./src/
    ports:
      - 5000:5000
    volumes:
      - ./src/app:/app
    environment: 
      TZ: Asia/Tokyo
      Flask_APP: app.py
      FLASK_ENV: development
    command: flask run -h 0.0.0.0 
    tty: true 
    depends_on: 
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge